Config = {};

Config.fatherNames = {
	"Benjamin",
	"Daniel",
	"Joshua",
	"Noah",
	"Andrew",
	"Juan",
	"Alex",
	"Isaac",
	"Evan",
	"Ethan",
	"Vincent",
	"Angel",
	"Diego",
	"Adrian",
	"Gabriel",
	"Michael",
	"Santiago",
	"Kevin",
	"Louis",
	"Samuel",
	"Anthony",
	"Claude",
	"Niko",
};

Config.motherNames = {
	"Hannah",
	"Aubrey",
	"Jasmine",
	"Gisele",
	"Amelia",
	"Isabella",
	"Zoe",
	"Ava",
	"Camila",
	"Violet",
	"Sophia",
	"Evelyn",
	"Nicole",
	"Ashley",
	"Gracie",
	"Brianna",
	"Natalie",
	"Olivia",
	"Elizabeth",
	"Charlotte",
	"Emma",
};

Config.AdvancedFaceParts = {
	{ label = "Nase 1", type = "nose_1" },
	{ label = "Nase 2", type = "nose_2" },
	{ label = "Nase 3", type = "nose_3" },
	{ label = "Nase 4", type = "nose_4" },
	{ label = "Nase 5", type = "nose_5" },
	{ label = "Nase 6", type = "nose_6" },
	{ label = "Augenbrauen 5", type = "eyebrows_5" },
	{ label = "Augenbrauen 6", type = "eyebrows_6" },
	{ label = "Wangen 1", type = "cheeks_1" },
	{ label = "Wangen 2", type = "cheeks_2" },
	{ label = "Wangen 3", type = "cheeks_3" },
	{ label = "Augenschielen", type = "eye_squint" },
	{ label = "Lippendicke", type = "lip_thickness" },
	{ label = "Kiefer 1", type = "jaw_1" },
	{ label = "Kiefer 2", type = "jaw_2" },
	{ label = "Kinn 1", type = "chin_1" },
	{ label = "Kinn 2", type = "chin_2" },
	{ label = "Kinn 3", type = "chin_3" },
	{ label = "Nackendicke", type = "neck_thickness" },
};

Config.skinContent = {
	{
		componentID = 2,
		name = "hair_1",
		name2 = "hair_2",
		label = "Haare",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "hair_color_1",
		name2 = "hair_color_2",
		label = "Hair colour",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHairColors() - 1,
		amountVariations = GetNumHairColors() - 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "beard_1",
		name2 = "beard_2",
		label = "Beard",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHeadOverlayValues(1) - 1,
		amountVariations = 10,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "beard_3",
		name2 = "beard_4",
		label = "Beard colour",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHairColors() - 1,
		amountVariations = GetNumHairColors() - 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "eyebrows_1",
		name2 = "eyebrows_2",
		label = "Eyebrows",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHeadOverlayValues(2) - 1,
		amountVariations = 10,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "eyebrows_3",
		name2 = "eyebrows_4",
		label = "Eyebrows colour",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHairColors() - 1,
		amountVariations = GetNumHairColors() - 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "makeup_1",
		name2 = "makeup_2",
		label = "Make-Up",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHeadOverlayValues(4) - 1,
		amountVariations = 10,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "makeup_3",
		name2 = "makeup_4",
		label = "Make-Up colour",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHairColors() - 1,
		amountVariations = GetNumHairColors() - 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "lipstick_1",
		name2 = "lipstick_2",
		label = "Lipstick",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHeadOverlayValues(8) - 1,
		amountVariations = 10,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = nil,
		name = "lipstick_3",
		name2 = "lipstick_4",
		label = "Lipstick colour",
		zoomOffset = 0.6,
		camOffset = 0.7,
		type = 3,
		amountComponents = GetNumHairColors() - 1,
		amountVariations = GetNumHairColors() - 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 11,
		name = "torso_1",
		name2 = "torso_2",
		label = "Torso",
		zoomOffset = 0.75,
		camOffset = 0.15,
		type = 1,
		blockedParts = {
			[0] = { 1, 4, 5 },
			[1] = { 1, 4, 5 },
		},
	},
	{
		componentID = 8,
		name = "tshirt_1",
		name2 = "tshirt_2",
		label = "T-Shirts",
		zoomOffset = 0.75,
		camOffset = 0.15,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 3,
		name = "arms",
		name2 = nil,
		label = "Arms",
		zoomOffset = 0.75,
		camOffset = 0.15,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 4,
		name = "pants_1",
		name2 = "pants_2",
		label = "Pants",
		zoomOffset = 0.8,
		camOffset = -0.5,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 6,
		name = "shoes_1",
		name2 = "shoes_2",
		label = "Shoes",
		zoomOffset = 0.8,
		camOffset = -0.8,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 7,
		name = "chain_1",
		name2 = "chain_2",
		label = "Chain",
		zoomOffset = 1.0,
		camOffset = 0.45,
		type = 1,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 1,
		name = "glasses_1",
		name2 = "glasses_2",
		label = "Glasses",
		zoomOffset = 0.6,
		camOffset = 0.65,
		type = 2,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
	{
		componentID = 2,
		name = "ears_1",
		name2 = "ears_2",
		label = "Ear accessoires",
		zoomOffset = 0.4,
		camOffset = 0.65,
		type = 2,
		blockedParts = {
			[0] = {},
			[1] = {},
		},
	},
};

Config.complexion = {
	"None",
	"Rosy Cheeks",
	"Stubble Rash",
	"Hot Flush",
	"Sunburn",
	"Bruised",
	"Alchoholic",
	"Patchy",
	"Totem",
	"Blood Vessels",
	"Damaged",
	"Pale",
	"Ghostly",
};

Config.sundamage = {
	"None",
	"Uneven",
	"Sandpaper",
	"Patchy",
	"Rough",
	"Leathery",
	"Textured",
	"Coarse",
	"Rugged",
	"Creased",
	"Cracked",
	"Gritty",
};

Config.eyebrows = {
	"None",
	"Balanced",
	"Fashion",
	"Cleopatra",
	"Quizzical",
	"Femme",
	"Seductive",
	"Pinched",
	"Chola",
	"Triomphe",
	"Carefree",
	"Curvaceous",
	"Rodent",
	"Double Tram",
	"Thin",
	"Penciled",
	"Mother Plucker",
	"Straight and Narrow",
	"Natural",
	"Fuzzy",
	"Unkempt",
	"Caterpillar",
	"Regular",
	"Mediterranean",
	"Groomed",
	"Bushels",
	"Feathered",
	"Prickly",
	"Monobrow",
	"Winged",
	"Triple Tram",
	"Arched Tram",
	"Cutouts",
	"Fade Away",
	"Solo Tram",
};

Config.eyeColors = {
	"Green",
	"Emerald",
	"Light Blue",
	"Ocean Blue",
	"Light Brown",
	"Dark Brown",
	"Hazel",
	"Dark Gray",
	"Light Gray",
	"Pink",
	"Yellow",
	"Purple",
	"Blackout",
	"Shades of Gray",
	"Tequila Sunrise",
	"Atomic",
	"Warp",
	"ECola",
	"Space Ranger",
	"Ying Yang",
	"Bullseye",
	"Lizard",
	"Dragon",
	"Extra Terrestrial",
	"Goat",
	"Smiley",
	"Possessed",
	"Demon",
	"Infected",
	"Alien",
	"Undead",
	"Zombie",
};

Config.ageing = {
	"None",
	"Crow's Feet",
	"First Signs",
	"Middle Aged",
	"Worry Lines",
	"Depression",
	"Distinguished",
	"Aged",
	"Weathered",
	"Wrinkled",
	"Sagging",
	"Tough Life",
	"Vintage",
	"Retired",
	"Junkie",
	"Geriatric",
};

Config.hairList = {
	-- male
	{
		{ ID = 0, Name = "Close Shave", Collection = "mpbeach_overlays", Overlay = "FM_Hair_Fuzz" },
		{ ID = 1, Name = "Buzzcut", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_001" },
		{ ID = 2, Name = "Faux Hawk", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_002" },
		{ ID = 3, Name = "Hipster", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_003" },
		{ ID = 4, Name = "Side Parting", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_004" },
		{ ID = 5, Name = "Shorter Cut", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_005" },
		{ ID = 6, Name = "Biker", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_006" },
		{ ID = 7, Name = "Ponytail", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_007" },
		{ ID = 8, Name = "Cornrows", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_008" },
		{ ID = 9, Name = "Slicked", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_009" },
		{ ID = 10, Name = "Short Brushed", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_013" },
		{ ID = 11, Name = "Spikey", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_002" },
		{ ID = 12, Name = "Caesar", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_011" },
		{ ID = 13, Name = "Chopped", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_012" },
		{ ID = 14, Name = "Dreads", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_014" },
		{ ID = 15, Name = "Long Hair", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_015" },
		{ ID = 16, Name = "Shaggy Curls", Collection = "multiplayer_overlays", Overlay = "NGBea_M_Hair_000" },
		{ ID = 17, Name = "Surfer Dude", Collection = "multiplayer_overlays", Overlay = "NGBea_M_Hair_001" },
		{ ID = 18, Name = "Short Side Part", Collection = "multiplayer_overlays", Overlay = "NGBus_M_Hair_000" },
		{ ID = 19, Name = "High Slicked Sides", Collection = "multiplayer_overlays", Overlay = "NGBus_M_Hair_001" },
		{ ID = 20, Name = "Long Slicked", Collection = "multiplayer_overlays", Overlay = "NGHip_M_Hair_000" },
		{ ID = 21, Name = "Hipster Youth", Collection = "multiplayer_overlays", Overlay = "NGHip_M_Hair_001" },
		{ ID = 22, Name = "Mullet", Collection = "multiplayer_overlays", Overlay = "NGInd_M_Hair_000" },
		{ ID = 24, Name = "Classic Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_M_Hair_000" },
		{ ID = 25, Name = "Palm Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_M_Hair_001" },
		{ ID = 26, Name = "Lightning Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_M_Hair_002" },
		{ ID = 27, Name = "Whipped Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_M_Hair_003" },
		{ ID = 28, Name = "Zig Zag Cornrows", Collection = "mplowrider2_overlays", Overlay = "LR_M_Hair_004" },
		{ ID = 29, Name = "Snail Cornrows", Collection = "mplowrider2_overlays", Overlay = "LR_M_Hair_005" },
		{ ID = 30, Name = "Hightop", Collection = "mplowrider2_overlays", Overlay = "LR_M_Hair_006" },
		{ ID = 31, Name = "Loose Swept Back", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_000_M" },
		{ ID = 32, Name = "Undercut Swept Back", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_001_M" },
		{ ID = 33, Name = "Undercut Swept Side", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_002_M" },
		{ ID = 34, Name = "Spiked Mohawk", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_003_M" },
		{ ID = 35, Name = "Mod", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_004_M" },
		{ ID = 36, Name = "Layered Mod", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_005_M" },
		{ ID = 72, Name = "Flattop", Collection = "mpgunrunning_overlays", Overlay = "MP_Gunrunning_Hair_M_000_M" },
		{
			ID = 73,
			Name = "Military Buzzcut",
			Collection = "mpgunrunning_overlays",
			Overlay = "MP_Gunrunning_Hair_M_001_M",
		},
	},

	-- female
	{
		{ ID = 0, Name = "Close Shave", Collection = "mpbeach_overlays", Overlay = "FM_Hair_Fuzz" },
		{ ID = 1, Name = "Short", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_001" },
		{ ID = 2, Name = "Layered Bob", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_002" },
		{ ID = 3, Name = "Pigtails", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_003" },
		{ ID = 4, Name = "Ponytail", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_004" },
		{ ID = 5, Name = "Braided Mohawk", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_005" },
		{ ID = 6, Name = "Braids", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_006" },
		{ ID = 7, Name = "Bob", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_007" },
		{ ID = 8, Name = "Faux Hawk", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_008" },
		{ ID = 9, Name = "French Twist", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_009" },
		{ ID = 10, Name = "Long Bob", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_010" },
		{ ID = 11, Name = "Loose Tied", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_011" },
		{ ID = 12, Name = "Pixie", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_012" },
		{ ID = 13, Name = "Shaved Bangs", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_013" },
		{ ID = 14, Name = "Top Knot", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_014" },
		{ ID = 15, Name = "Wavy Bob", Collection = "multiplayer_overlays", Overlay = "NG_M_Hair_015" },
		{ ID = 16, Name = "Messy Bun", Collection = "multiplayer_overlays", Overlay = "NGBea_F_Hair_000" },
		{ ID = 17, Name = "Pin Up Girl", Collection = "multiplayer_overlays", Overlay = "NGBea_F_Hair_001" },
		{ ID = 18, Name = "Tight Bun", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_007" },
		{ ID = 19, Name = "Twisted Bob", Collection = "multiplayer_overlays", Overlay = "NGBus_F_Hair_000" },
		{ ID = 20, Name = "Flapper Bob", Collection = "multiplayer_overlays", Overlay = "NGBus_F_Hair_001" },
		{ ID = 21, Name = "Big Bangs", Collection = "multiplayer_overlays", Overlay = "NGBea_F_Hair_001" },
		{ ID = 22, Name = "Braided Top Knot", Collection = "multiplayer_overlays", Overlay = "NGHip_F_Hair_000" },
		{ ID = 23, Name = "Mullet", Collection = "multiplayer_overlays", Overlay = "NGInd_F_Hair_000" },
		{ ID = 25, Name = "Pinched Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_F_Hair_000" },
		{ ID = 26, Name = "Leaf Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_F_Hair_001" },
		{ ID = 27, Name = "Zig Zag Cornrows", Collection = "mplowrider_overlays", Overlay = "LR_F_Hair_002" },
		{ ID = 28, Name = "Pigtail Bangs", Collection = "mplowrider2_overlays", Overlay = "LR_F_Hair_003" },
		{ ID = 29, Name = "Wave Braids", Collection = "mplowrider2_overlays", Overlay = "LR_F_Hair_003" },
		{ ID = 30, Name = "Coil Braids", Collection = "mplowrider2_overlays", Overlay = "LR_F_Hair_004" },
		{ ID = 31, Name = "Rolled Quiff", Collection = "mplowrider2_overlays", Overlay = "LR_F_Hair_006" },
		{ ID = 32, Name = "Loose Swept Back", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_000_F" },
		{ ID = 33, Name = "Undercut Swept Back", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_001_F" },
		{ ID = 34, Name = "Undercut Swept Side", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_002_F" },
		{ ID = 35, Name = "Spiked Mohawk", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_003_F" },
		{ ID = 36, Name = "Bandana and Braid", Collection = "multiplayer_overlays", Overlay = "NG_F_Hair_003" },
		{ ID = 37, Name = "Layered Mod", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_006_F" },
		{ ID = 38, Name = "Skinbyrd", Collection = "mpbiker_overlays", Overlay = "MP_Biker_Hair_004_F" },
		{ ID = 76, Name = "Neat Bun", Collection = "mpgunrunning_overlays", Overlay = "MP_Gunrunning_Hair_F_000_F" },
		{ ID = 77, Name = "Short Bob", Collection = "mpgunrunning_overlays", Overlay = "MP_Gunrunning_Hair_F_001_F" },
	},
};

Config.MaleTorsoData = {
	[0] = { arms = 0, validShirts = { 15 } },
	[1] = { arms = 0, validShirts = { 15 } },
	[2] = { arms = 2, validShirts = { 15 } },
	[3] = { arms = 6, validShirts = { 0 } },
	[4] = { arms = 12, validShirts = { 0 } },
	[5] = { arms = 5, validShirts = { 15 } },
	[6] = { arms = 1, validShirts = { 24 } },
	[7] = { arms = 1, validShirts = { 0 } },
	[8] = { arms = 8, validShirts = { 15 } },
	[9] = { arms = 0, validShirts = { 15 } },
	[10] = { arms = 4, validShirts = { 28 } },
	[11] = { arms = 4, validShirts = { 22 } },
	[12] = { arms = 1, validShirts = { 15 } },
	[13] = { arms = 11, validShirts = { 15 } },
	[14] = { arms = 6, validShirts = { 15 } },
	[15] = { arms = 15, validShirts = { 15 } },
	[16] = { arms = 0, validShirts = { 15 } },
	[17] = { arms = 5, validShirts = { 15 } },
	[18] = { arms = 0, validShirts = { 15 } },
	[19] = { arms = 1, validShirts = { 20 } },
	[20] = { arms = 1, validShirts = { 13 } },
	[21] = { arms = 11, validShirts = { 6 } },
	[22] = { arms = 0, validShirts = { 15 } },
	[23] = { arms = 12, validShirts = { 11 } },
	[24] = { arms = 12, validShirts = { 12 } },
	[25] = { arms = 11, validShirts = { 7 } },
	[26] = { arms = 11, validShirts = { 15 } },
	[27] = { arms = 1, validShirts = { 12 } },
	[28] = { arms = 1, validShirts = { 12 } },
	[29] = { arms = 12, validShirts = { 31 } },
	[30] = { arms = 12, validShirts = { 32 } },
	[31] = { arms = 12, validShirts = { 32 } },
	[32] = { arms = 12, validShirts = { 32 } },
	[33] = { arms = 0, validShirts = { 15 } },
	[34] = { arms = 0, validShirts = { 15 } },
	[35] = { arms = 4, validShirts = { 28 } },
	[36] = { arms = 5, validShirts = { 15 } },
	[37] = { arms = 6, validShirts = { 18 } },
	[38] = { arms = 8, validShirts = { 15 } },
	[39] = { arms = 0, validShirts = { 15 } },
	[40] = { arms = 4, validShirts = { 22 } },
	[41] = { arms = 6, validShirts = { 15 } },
	[42] = { arms = 11, validShirts = { 15 } },
	[43] = { arms = 11, validShirts = { 15 } },
	[44] = { arms = 0, validShirts = { 15 } },
	[45] = { arms = 0, validShirts = { 50 } },
	[46] = { arms = 6, validShirts = { 17 } },
	[47] = { arms = 0, validShirts = { 15 } },
	[48] = { arms = 1, validShirts = { 72 } },
	[49] = { arms = 1, validShirts = { 15 } },
	[50] = { arms = 1, validShirts = { 15 } },
	[51] = { arms = 1, validShirts = { 15 } },
	[52] = { arms = 2, validShirts = { 15 } },
	[53] = { arms = 1, validShirts = { 15 } },
	[54] = { arms = 1, validShirts = { 74 } },
	[55] = { arms = 0, validShirts = { 15 } },
	[56] = { arms = 0, validShirts = { 15 } },
	[57] = { arms = 0, validShirts = { 15 } },
	[58] = { arms = 1, validShirts = { 9 } },
	[59] = { arms = 1, validShirts = { 63 } },
	[60] = { arms = 11, validShirts = { 10 } },
	[61] = { arms = 11, validShirts = { 15 } },
	[62] = { arms = 6, validShirts = { 23 } },
	[63] = { arms = 0, validShirts = { 15 } },
	[64] = { arms = 1, validShirts = { 18 } },
	[65] = { arms = 14, validShirts = { 15 } },
	[66] = { arms = 8, validShirts = { 15 } }, --
	[67] = { arms = 6, validShirts = { 15 } }, --
	[68] = { arms = 0, validShirts = { 14 } },
	[69] = { arms = 0, validShirts = { 14 } },
	[70] = { arms = 1, validShirts = { 12 } },
	[71] = { arms = 0, validShirts = { 15 } },
	[72] = { arms = 0, validShirts = { 16 } },
	[73] = { arms = 0, validShirts = { 15 } },
	[74] = { arms = 0, validShirts = { 16 } },
	[75] = { arms = 0, validShirts = { 15 } },
	[76] = { arms = 0, validShirts = { 21 } },
	[77] = { arms = 1, validShirts = { 1 } },
	[78] = { arms = 1, validShirts = { 15 } },
	[79] = { arms = 1, validShirts = { 15 } },
	[80] = { arms = 2, validShirts = { 15 } },
	[81] = { arms = 0, validShirts = { 15 } },
	[82] = { arms = 0, validShirts = { 15 } },
	[83] = { arms = 0, validShirts = { 15 } },
	[84] = { arms = 0, validShirts = { 15 } },
	[85] = { arms = 0, validShirts = { 15 } },
	[86] = { arms = 0, validShirts = { 15 } },
	[87] = { arms = 0, validShirts = { 15 } },
	[88] = { arms = 1, validShirts = { 16 } },
	[89] = { arms = 1, validShirts = { 15 } },
	[90] = { arms = 1, validShirts = { 15 } },
	[91] = { arms = 15, validShirts = { 15 } },
	[92] = { arms = 14, validShirts = { 15 } },
	[93] = { arms = 0, validShirts = { 15 } },
	[94] = { arms = 0, validShirts = { 15 } },
	[95] = { arms = 11, validShirts = { 15 } },
	[96] = { arms = 11, validShirts = { 15 } },
	[97] = { arms = 0, validShirts = { 15 } },
	[98] = { arms = 0, validShirts = { 15 } },
	[99] = { arms = 4, validShirts = { 31 } },
	[100] = { arms = 4, validShirts = { 31 } },
	[101] = { arms = 4, validShirts = { 31 } },
	[102] = { arms = 4, validShirts = { 31 } },
	[103] = { arms = 4, validShirts = { 31 } },
	[104] = { arms = 4, validShirts = { 31 } },
	[105] = { arms = 2, validShirts = { 15 } },
	[106] = { arms = 1, validShirts = { 16 } },
	[107] = { arms = 1, validShirts = { 15 } },
	[108] = { arms = 14, validShirts = { 15 } },
	[109] = { arms = 5, validShirts = { 15 } },
	[110] = { arms = 4, validShirts = { 15 } },
	[111] = { arms = 4, validShirts = { 15 } },
	[112] = { arms = 4, validShirts = { 31 } },
	[113] = { arms = 6, validShirts = { 15 } },
	[114] = { arms = 14, validShirts = { 15 } },
	[115] = { arms = 14, validShirts = { 16 } },
	[116] = { arms = 14, validShirts = { 15 } },
	[117] = { arms = 14, validShirts = { 15 } },
	[118] = { arms = 14, validShirts = { 16 } },
	[119] = { arms = 14, validShirts = { 13 } },
	[120] = { arms = 11, validShirts = { 6 } },
	[121] = { arms = 11, validShirts = { 15 } },
	[122] = { arms = 6, validShirts = { 16 } },
	[123] = { arms = 0, validShirts = { 15 } },
	[124] = { arms = 1, validShirts = { 16 } },
	[125] = { arms = 1, validShirts = { 15 } },
	[126] = { arms = 1, validShirts = { 15 } },
	[127] = { arms = 1, validShirts = { 16 } },
	[128] = { arms = 8, validShirts = { 15 } },
	[129] = { arms = 1, validShirts = { 15 } },
	[130] = { arms = 12, validShirts = { 16 } },
	[131] = { arms = 0, validShirts = { 15 } },
	[132] = { arms = 0, validShirts = { 15 } },
	[133] = { arms = 11, validShirts = { 15 } },
	[134] = { arms = 11, validShirts = { 15 } },
	[135] = { arms = 11, validShirts = { 15 } },
	[136] = { arms = 8, validShirts = { 23 } },
	[137] = { arms = 11, validShirts = { 6 } },
	[138] = { arms = 11, validShirts = { 15 } },
	[139] = { arms = 4, validShirts = { 15 } },
	[140] = { arms = 4, validShirts = { 31 } },
	[141] = { arms = 6, validShirts = { 15 } },
	[142] = { arms = 6, validShirts = { 16 } },
	[143] = { arms = 6, validShirts = { 15 } },
	[144] = { arms = 6, validShirts = { 15 } },
	[145] = { arms = 14, validShirts = { 15 } },
	[146] = { arms = 0, validShirts = { 15 } },
	[147] = { arms = 4, validShirts = { 15 } },
	[148] = { arms = 4, validShirts = { 15 } },
	[149] = { arms = 14, validShirts = { 15 } },
	[150] = { arms = 14, validShirts = { 15 } },
	[151] = { arms = 14, validShirts = { 16 } },
	[152] = { arms = 14, validShirts = { 15 } },
	[153] = { arms = 14, validShirts = { 15 } },
	[154] = { arms = 14, validShirts = { 15 } },
	[155] = { arms = 14, validShirts = { 15 } },
	[156] = { arms = 14, validShirts = { 16 } },
	[157] = { arms = 0, validShirts = { 103 } },
	[158] = { arms = 15, validShirts = { 15 } },
	[159] = { arms = 15, validShirts = { 15 } },
	[160] = { arms = 15, validShirts = { 16 } },
	[161] = { arms = 14, validShirts = { 14 } },
	[162] = { arms = 15, validShirts = { 15 } },
	[163] = { arms = 14, validShirts = { 16 } },
	[164] = { arms = 11, validShirts = { 15 } },
	[165] = { arms = 15, validShirts = { 15 } },
	[166] = { arms = 12, validShirts = { 16 } },
	[167] = { arms = 12, validShirts = { 16 } },
	[168] = { arms = 14, validShirts = { 2 } },
	[169] = { arms = 14, validShirts = { 16 } },
	[170] = { arms = 5, validShirts = { 16 } },
	[171] = { arms = 6, validShirts = { 15 } },
	[172] = { arms = 14, validShirts = { 1 } },
	[173] = { arms = 15, validShirts = { 15 } },
	[174] = { arms = 14, validShirts = { 15 } },
	[175] = { arms = 15, validShirts = { 15 } },
	[176] = { arms = 15, validShirts = { 5 } },
	[177] = { arms = 15, validShirts = { 15 } },
	[178] = { arms = 14, validShirts = { 15 } },
	[179] = { arms = 15, validShirts = { 0 } },
	[180] = { arms = 15, validShirts = { 15 } },
	[181] = { arms = 14, validShirts = { 16 } },
	[182] = { arms = 14, validShirts = { 15 } },
	[183] = { arms = 12, validShirts = { 32 } },
	[184] = { arms = 12, validShirts = { 15 } },
	[185] = { arms = 15, validShirts = { 16 } },
	[186] = { arms = 15, validShirts = { 16 } },
	[187] = { arms = 12, validShirts = { 14 } },
	[188] = { arms = 12, validShirts = { 16 } },
	[189] = { arms = 12, validShirts = { 16 } },
	[190] = { arms = 12, validShirts = { 15 } },
	[191] = { arms = 12, validShirts = { 16 } },
	[192] = { arms = 12, validShirts = { 16 } },
	[193] = { arms = 11, validShirts = { 15 } },
	[194] = { arms = 11, validShirts = { 15 } },
	[195] = { arms = 11, validShirts = { 15 } },
	[196] = { arms = 11, validShirts = { 15 } },
	[197] = { arms = 11, validShirts = { 15 } },
	[198] = { arms = 5, validShirts = { 15 } },
	[199] = { arms = 5, validShirts = { 15 } },
	[200] = { arms = 4, validShirts = { 15 } },
	[201] = { arms = 3, validShirts = { 15 } },
	[202] = { arms = 5, validShirts = { 15 } },
	[203] = { arms = 4, validShirts = { 15 } },
	[204] = { arms = 5, validShirts = { 2 } },
	[205] = { arms = 5, validShirts = { 15 } },
	[206] = { arms = 5, validShirts = { 15 } },
	[207] = { arms = 5, validShirts = { 15 } },
	[208] = { arms = 0, validShirts = { 15 } },
	[209] = { arms = 0, validShirts = { 15 } },
	[210] = { arms = 0, validShirts = { 15 } },
	[211] = { arms = 0, validShirts = { 15 } },
	[212] = { arms = 0, validShirts = { 16 } },
	[213] = { arms = 2, validShirts = { 15 } },
	[214] = { arms = 1, validShirts = { 15 } },
	[215] = { arms = 1, validShirts = { 16 } },
	[216] = { arms = 2, validShirts = { 16 } },
	[217] = { arms = 1, validShirts = { 15 } },
	[218] = { arms = 1, validShirts = { 15 } },
	[219] = { arms = 2, validShirts = { 15 } },
	[220] = { arms = 2, validShirts = { 15 } },
	[221] = { arms = 1, validShirts = { 15 } },
	[222] = { arms = 11, validShirts = { 15 } },
	[223] = { arms = 5, validShirts = { 15 } },
	[224] = { arms = 1, validShirts = { 15 } },
	[225] = { arms = 8, validShirts = { 15 } },
	[226] = { arms = 0, validShirts = { 15 } },
	[227] = { arms = 4, validShirts = { 15 } },
	[228] = { arms = 4, validShirts = { 15 } },
	[229] = { arms = 4, validShirts = { 15 } },
	[230] = { arms = 5, validShirts = { 16 } },
	[231] = { arms = 4, validShirts = { 71 } },
	[232] = { arms = 4, validShirts = { 54 } },
	[233] = { arms = 4, validShirts = { 23 } },
	[234] = { arms = 0, validShirts = { 15 } },
	[235] = { arms = 0, validShirts = { 15 } },
	[236] = { arms = 0, validShirts = { 15 } },
	[237] = { arms = 5, validShirts = { 15 } },
	[238] = { arms = 5, validShirts = { 15 } },
	[239] = { arms = 2, validShirts = { 15 } },
	[240] = { arms = 4, validShirts = { 21 } },
	[241] = { arms = 0, validShirts = { 15 } },
	[242] = { arms = 0, validShirts = { 15 } },
	[243] = { arms = 0, validShirts = { 15 } },
	[244] = { arms = 1, validShirts = { 71 } },
	[245] = { arms = 1, validShirts = { 15 } },
	[246] = { arms = 3, validShirts = { 15 } },
	[247] = { arms = 5, validShirts = { 15 } },
	[248] = { arms = 6, validShirts = { 15 } },
	[249] = { arms = 6, validShirts = { 15 } },
	[250] = { arms = 0, validShirts = { 15 } },
	[251] = { arms = 0, validShirts = { 15 } },
	[252] = { arms = 15, validShirts = { 15 } },
	[253] = { arms = 15, validShirts = { 15 } },
	[254] = { arms = 8, validShirts = { 15 } },
	[255] = { arms = 8, validShirts = { 15 } },
	[256] = { arms = 8, validShirts = { 15 } },
	[257] = { arms = 12, validShirts = { 15 } },
	[258] = { arms = 14, validShirts = { 20 } },
	[259] = { arms = 14, validShirts = { 15 } },
	[260] = { arms = 0, validShirts = { 15 } },
	[261] = { arms = 0, validShirts = { 16 } },
	[262] = { arms = 0, validShirts = { 15 } },
	[263] = { arms = 0, validShirts = { 15 } },
	[264] = { arms = 6, validShirts = { 2 } },
	[265] = { arms = 0, validShirts = { 15 } },
	[266] = { arms = 0, validShirts = { 16 } },
	[267] = { arms = 0, validShirts = { 16 } },
	[268] = { arms = 0, validShirts = { 16 } },
	[269] = { arms = 0, validShirts = { 16 } },
	[270] = { arms = 4, validShirts = { 15 } },
	[271] = { arms = 0, validShirts = { 15 } },
	[272] = { arms = 0, validShirts = { 15 } },
	[273] = { arms = 0, validShirts = { 15 } },
	[274] = { arms = 3, validShirts = { 15 } },
	[275] = { arms = 4, validShirts = { 15 } },
	[276] = { arms = 4, validShirts = { 15 } },
	[277] = { arms = 164, validShirts = { 15 } },
	[278] = { arms = 165, validShirts = { 15 } },
	[279] = { arms = 1, validShirts = { 15 } },
	[280] = { arms = 1, validShirts = { 15 } },
	[281] = { arms = 1, validShirts = { 15 } },
	[282] = { arms = 0, validShirts = { 15 } },
	[283] = { arms = 166, validShirts = { 15 } },
	[284] = { arms = 4, validShirts = { 15 } },
	[285] = { arms = 165, validShirts = { 15 } },
	[286] = { arms = 167, validShirts = { 15 } },
	[287] = { arms = 3, validShirts = { 15 } },
	[288] = { arms = 4, validShirts = { 15 } },
	[289] = { arms = 2, validShirts = { 15 } },
};

Config.FemaleTorsoData = {
	[0] = { arms = 0, validShirts = { 15 } },
	[1] = { arms = 1, validShirts = { 11 } },
	[2] = { arms = 11, validShirts = { 15 } },
	[3] = { arms = 3, validShirts = { 14 } },
	[4] = { arms = 4, validShirts = { 15 } },
	[5] = { arms = 4, validShirts = { 15 } },
	[6] = { arms = 5, validShirts = { 20 } },
	[7] = { arms = 6, validShirts = { 20 } },
	[8] = { arms = 1, validShirts = { 0 } },
	[9] = { arms = 0, validShirts = { 15 } },
	[10] = { arms = 0, validShirts = { 16 } },
	[11] = { arms = 4, validShirts = { 11 } },
	[12] = { arms = 15, validShirts = { 15 } },
	[13] = { arms = 15, validShirts = { 15 } },
	[14] = { arms = 14, validShirts = { 15 } },
	[15] = { arms = 15, validShirts = { 15 } },
	[16] = { arms = 15, validShirts = { 15 } },
	[17] = { arms = 9, validShirts = { 15 } },
	[18] = { arms = 15, validShirts = { 14 } },
	[19] = { arms = 15, validShirts = { 15 } },
	[20] = { arms = 1, validShirts = { 16 } },
	[21] = { arms = 11, validShirts = { 15 } },
	[22] = { arms = 15, validShirts = { 14 } },
	[23] = { arms = 15, validShirts = { 15 } },
	[24] = { arms = 5, validShirts = { 0 } },
	[25] = { arms = 6, validShirts = { 0 } },
	[26] = { arms = 15, validShirts = { 15 } },
	[27] = { arms = 0, validShirts = { 15 } },
	[28] = { arms = 0, validShirts = { 24 } },
	[29] = { arms = 14, validShirts = { 32 } },
	[30] = { arms = 2, validShirts = { 15 } },
	[31] = { arms = 5, validShirts = { 16 } },
	[32] = { arms = 15, validShirts = { 15 } },
	[33] = { arms = 15, validShirts = { 15 } },
	[34] = { arms = 7, validShirts = { 11 } },
	[35] = { arms = 9, validShirts = { 11 } },
	[36] = { arms = 15, validShirts = { 15 } },
	[37] = { arms = 15, validShirts = { 15 } },
	[38] = { arms = 2, validShirts = { 15 } },
	[39] = { arms = 1, validShirts = { 15 } },
	[40] = { arms = 2, validShirts = { 15 } },
	[41] = { arms = 1, validShirts = { 15 } },
	[42] = { arms = 1, validShirts = { 15 } },
	[43] = { arms = 3, validShirts = { 15 } },
	[44] = { arms = 3, validShirts = { 15 } },
	[45] = { arms = 3, validShirts = { 15 } },
	[46] = { arms = 3, validShirts = { 15 } },
	[47] = { arms = 5, validShirts = { 15 } },
	[48] = { arms = 14, validShirts = { 15 } },
	[49] = { arms = 14, validShirts = { 15 } },
	[50] = { arms = 14, validShirts = { 15 } },
	[51] = { arms = 14, validShirts = { 37 } },
	[52] = { arms = 14, validShirts = { 37 } },
	[53] = { arms = 14, validShirts = { 37 } },
	[54] = { arms = 5, validShirts = { 15 } },
	[55] = { arms = 5, validShirts = { 15 } },
	[56] = { arms = 2, validShirts = { 15 } },
	[57] = { arms = 5, validShirts = { 38 } },
	[58] = { arms = 5, validShirts = { 21 } },
	[59] = { arms = 3, validShirts = { 8 } },
	[60] = { arms = 3, validShirts = { 8 } },
	[61] = { arms = 3, validShirts = { 8 } },
	[62] = { arms = 7, validShirts = { 15 } },
	[63] = { arms = 7, validShirts = { 15 } },
	[64] = { arms = 6, validShirts = { 16 } },
	[65] = { arms = 6, validShirts = { 13 } },
	[66] = { arms = 6, validShirts = { 14 } },
	[67] = { arms = 2, validShirts = { 15 } },
	[68] = { arms = 14, validShirts = { 15 } },
	[69] = { arms = 7, validShirts = { 15 } },
	[70] = { arms = 7, validShirts = { 15 } },
	[71] = { arms = 9, validShirts = { 15 } },
	[72] = { arms = 9, validShirts = { 15 } },
	[73] = { arms = 14, validShirts = { 15 } },
	[74] = { arms = 15, validShirts = { 15 } },
	[75] = { arms = 9, validShirts = { 15 } },
	[76] = { arms = 9, validShirts = { 14 } },
	[77] = { arms = 9, validShirts = { 14 } },
	[78] = { arms = 9, validShirts = { 14 } },
	[79] = { arms = 9, validShirts = { 14 } },
	[80] = { arms = 9, validShirts = { 14 } },
	[81] = { arms = 9, validShirts = { 14 } },
	[82] = { arms = 15, validShirts = { 32 } },
	[83] = { arms = 9, validShirts = { 9 } },
	[84] = { arms = 0, validShirts = { 0 } },
	[85] = { arms = 0, validShirts = { 15 } },
	[86] = { arms = 0, validShirts = { 15 } },
	[87] = { arms = 9, validShirts = { 14 } },
	[88] = { arms = 0, validShirts = { 14 } },
	[89] = { arms = 0, validShirts = { 14 } },
	[90] = { arms = 6, validShirts = { 0 } },
	[91] = { arms = 6, validShirts = { 0 } },
	[92] = { arms = 5, validShirts = { 0 } },
	[93] = { arms = 5, validShirts = { 38 } },
	[94] = { arms = 9, validShirts = { 48 } },
	[95] = { arms = 5, validShirts = { 38 } },
	[96] = { arms = 2, validShirts = { 9 } },
	[97] = { arms = 6, validShirts = { 0 } },
	[98] = { arms = 6, validShirts = { 0 } },
	[99] = { arms = 6, validShirts = { 0 } },
	[100] = { arms = 11, validShirts = { 0 } },
	[101] = { arms = 15, validShirts = { 14 } },
	[102] = { arms = 9, validShirts = { 14 } },
	[103] = { arms = 7, validShirts = { 14 } },
	[104] = { arms = 3, validShirts = { 76 } },
	[105] = { arms = 15, validShirts = { 15 } },
	[106] = { arms = 7, validShirts = { 15 } },
	[107] = { arms = 7, validShirts = { 0 } },
	[108] = { arms = 7, validShirts = { 1 } },
	[109] = { arms = 7, validShirts = { 1 } },
	[110] = { arms = 7, validShirts = { 1 } },
	[111] = { arms = 15, validShirts = { 14 } },
	[112] = { arms = 15, validShirts = { 15 } },
	[113] = { arms = 15, validShirts = { 15 } },
	[114] = { arms = 15, validShirts = { 14 } },
	[115] = { arms = 15, validShirts = { 15 } },
	[116] = { arms = 15, validShirts = { 14 } },
	[117] = { arms = 11, validShirts = { 15 } },
	[118] = { arms = 11, validShirts = { 15 } },
	[119] = { arms = 11, validShirts = { 15 } },
	[120] = { arms = 9, validShirts = { 11 } },
	[121] = { arms = 9, validShirts = { 11 } },
	[122] = { arms = 9, validShirts = { 10 } },
	[123] = { arms = 9, validShirts = { 11 } },
	[124] = { arms = 14, validShirts = { 14 } },
	[125] = { arms = 0, validShirts = { 14 } },
	[126] = { arms = 1, validShirts = { 14 } },
	[127] = { arms = 3, validShirts = { 3 } },
	[128] = { arms = 14, validShirts = { 3 } },
	[129] = { arms = 14, validShirts = { 3 } },
	[130] = { arms = 14, validShirts = { 3 } },
	[131] = { arms = 14, validShirts = { 3 } },
	[132] = { arms = 14, validShirts = { 3 } },
	[133] = { arms = 7, validShirts = { 20 } },
	[134] = { arms = 3, validShirts = { 65 } },
	[135] = { arms = 3, validShirts = { 14 } },
	[136] = { arms = 3, validShirts = { 14 } },
	[137] = { arms = 5, validShirts = { 13 } },
	[138] = { arms = 6, validShirts = { 0 } },
	[139] = { arms = 6, validShirts = { 0 } },
	[140] = { arms = 5, validShirts = { 3 } },
	[141] = { arms = 0, validShirts = { 3 } },
	[142] = { arms = 0, validShirts = { 3 } },
	[143] = { arms = 4, validShirts = { 3 } },
	[144] = { arms = 9, validShirts = { 14 } },
	[145] = { arms = 9, validShirts = { 14 } },
	[146] = { arms = 7, validShirts = { 14 } },
	[147] = { arms = 2, validShirts = { 14 } },
	[148] = { arms = 5, validShirts = { 0 } },
	[149] = { arms = 3, validShirts = { 3 } },
	[150] = { arms = 3, validShirts = { 3 } },
	[151] = { arms = 3, validShirts = { 3 } },
	[152] = { arms = 7, validShirts = { 3 } },
	[153] = { arms = 7, validShirts = { 0 } },
	[154] = { arms = 12, validShirts = { 0 } },
	[155] = { arms = 12, validShirts = { 0 } },
	[156] = { arms = 12, validShirts = { 0 } },
	[157] = { arms = 12, validShirts = { 0 } },
	[158] = { arms = 9, validShirts = { 0 } },
	[159] = { arms = 12, validShirts = { 0 } },
	[160] = { arms = 6, validShirts = { 0 } },
	[161] = { arms = 2, validShirts = { 14 } },
	[162] = { arms = 1, validShirts = { 14 } },
	[163] = { arms = 1, validShirts = { 16 } },
	[164] = { arms = 1, validShirts = { 16 } },
	[165] = { arms = 1, validShirts = { 16 } },
	[166] = { arms = 1, validShirts = { 16 } },
	[167] = { arms = 4, validShirts = { 16 } },
	[168] = { arms = 4, validShirts = { 14 } },
	[169] = { arms = 4, validShirts = { 14 } },
	[170] = { arms = 4, validShirts = { 14 } },
	[171] = { arms = 4, validShirts = { 14 } },
	[172] = { arms = 3, validShirts = { 14 } },
	[173] = { arms = 4, validShirts = { 15 } },
	[174] = { arms = 4, validShirts = { 13 } },
	[175] = { arms = 4, validShirts = { 13 } },
	[176] = { arms = 15, validShirts = { 15 } },
	[177] = { arms = 4, validShirts = { 15 } },
	[178] = { arms = 12, validShirts = { 15 } },
	[179] = { arms = 11, validShirts = { 10 } },
	[180] = { arms = 9, validShirts = { 14 } },
	[181] = { arms = 4, validShirts = { 26 } },
	[182] = { arms = 4, validShirts = { 25 } },
	[183] = { arms = 4, validShirts = { 20 } },
	[184] = { arms = 14, validShirts = { 14 } },
	[185] = { arms = 6, validShirts = { 5 } },
	[186] = { arms = 15, validShirts = { 16 } },
	[187] = { arms = 6, validShirts = { 51 } },
	[188] = { arms = 6, validShirts = { 47 } },
	[189] = { arms = 6, validShirts = { 69 } },
	[190] = { arms = 6, validShirts = { 69 } },
	[191] = { arms = 6, validShirts = { 72 } },
	[192] = { arms = 12, validShirts = { 68 } },
	[193] = { arms = 12, validShirts = { 69 } },
	[194] = { arms = 11, validShirts = { 57 } },
	[195] = { arms = 15, validShirts = { 17 } },
	[196] = { arms = 3, validShirts = { 17 } },
	[197] = { arms = 3, validShirts = { 17 } },
	[198] = { arms = 4, validShirts = { 17 } },
	[199] = { arms = 4, validShirts = { 17 } },
	[200] = { arms = 4, validShirts = { 17 } },
	[201] = { arms = 4, validShirts = { 17 } },
	[202] = { arms = 14, validShirts = { 14 } },
	[203] = { arms = 13, validShirts = { 9 } },
	[204] = { arms = 11, validShirts = { 9 } },
	[205] = { arms = 11, validShirts = { 9 } },
	[206] = { arms = 6, validShirts = { 9 } },
	[207] = { arms = 11, validShirts = { 9 } },
	[208] = { arms = 11, validShirts = { 9 } },
	[209] = { arms = 11, validShirts = { 9 } },
	[210] = { arms = 11, validShirts = { 9 } },
	[211] = { arms = 11, validShirts = { 9 } },
	[212] = { arms = 14, validShirts = { 9 } },
	[213] = { arms = 3, validShirts = { 9 } },
	[214] = { arms = 3, validShirts = { 9 } },
	[215] = { arms = 3, validShirts = { 9 } },
	[216] = { arms = 5, validShirts = { 121 } },
	[217] = { arms = 4, validShirts = { 72 } },
	[218] = { arms = 3, validShirts = { 70 } },
	[219] = { arms = 3, validShirts = { 123 } },
	[220] = { arms = 4, validShirts = { 123 } },
	[221] = { arms = 4, validShirts = { 122 } },
	[222] = { arms = 4, validShirts = { 122 } },
	[223] = { arms = 15, validShirts = { 122 } },
	[224] = { arms = 14, validShirts = { 9 } },
	[225] = { arms = 15, validShirts = { 9 } },
	[226] = { arms = 11, validShirts = { 9 } },
	[227] = { arms = 7, validShirts = { 9 } },
	[228] = { arms = 7, validShirts = { 9 } },
	[229] = { arms = 11, validShirts = { 9 } },
	[230] = { arms = 9, validShirts = { 9 } },
	[231] = { arms = 9, validShirts = { 9 } },
	[232] = { arms = 9, validShirts = { 9 } },
	[233] = { arms = 11, validShirts = { 27 } },
	[234] = { arms = 7, validShirts = { 27 } },
	[235] = { arms = 9, validShirts = { 14 } },
	[236] = { arms = 14, validShirts = { 14 } },
	[237] = { arms = 14, validShirts = { 14 } },
	[238] = { arms = 0, validShirts = { 14 } },
	[239] = { arms = 0, validShirts = { 14 } },
	[240] = { arms = 5, validShirts = { 26 } },
	[241] = { arms = 3, validShirts = { 8 } },
	[242] = { arms = 6, validShirts = { 8 } },
	[243] = { arms = 6, validShirts = { 26 } },
	[244] = { arms = 0, validShirts = { 14 } },
	[245] = { arms = 0, validShirts = { 14 } },
	[246] = { arms = 0, validShirts = { 14 } },
	[247] = { arms = 4, validShirts = { 14 } },
	[248] = { arms = 6, validShirts = { 20 } },
	[249] = { arms = 0, validShirts = { 19 } },
	[250] = { arms = 0, validShirts = { 19 } },
	[251] = { arms = 0, validShirts = { 19 } },
	[252] = { arms = 0, validShirts = { 19 } },
	[253] = { arms = 14, validShirts = { 19 } },
	[254] = { arms = 8, validShirts = { 9 } },
	[255] = { arms = 4, validShirts = { 9 } },
	[256] = { arms = 4, validShirts = { 9 } },
	[257] = { arms = 3, validShirts = { 9 } },
	[258] = { arms = 14, validShirts = { 9 } },
	[259] = { arms = 14, validShirts = { 9 } },
	[260] = { arms = 15, validShirts = { 9 } },
	[261] = { arms = 15, validShirts = { 9 } },
	[262] = { arms = 7, validShirts = { 9 } },
	[263] = { arms = 14, validShirts = { 14 } },
	[264] = { arms = 3, validShirts = { 6 } },
	[265] = { arms = 3, validShirts = { 6 } },
	[266] = { arms = 3, validShirts = { 6 } },
	[267] = { arms = 4, validShirts = { 6 } },
	[268] = { arms = 4, validShirts = { 6 } },
	[269] = { arms = 4, validShirts = { 6 } },
	[270] = { arms = 4, validShirts = { 0 } },
	[271] = { arms = 3, validShirts = { 3 } },
	[272] = { arms = 3, validShirts = { 3 } },
	[273] = { arms = 5, validShirts = { 3 } },
	[274] = { arms = 5, validShirts = { 3 } },
	[275] = { arms = 5, validShirts = { 20 } },
	[276] = { arms = 6, validShirts = { 20 } },
	[277] = { arms = 6, validShirts = { 26 } },
	[278] = { arms = 6, validShirts = { 26 } },
	[279] = { arms = 15, validShirts = { 14 } },
	[280] = { arms = 14, validShirts = { 14 } },
	[281] = { arms = 14, validShirts = { 14 } },
	[282] = { arms = 14, validShirts = { 14 } },
	[283] = { arms = 12, validShirts = { 14 } },
	[284] = { arms = 4, validShirts = { 14 } },
	[285] = { arms = 3, validShirts = { 14 } },
	[286] = { arms = 0, validShirts = { 14 } },
	[287] = { arms = 8, validShirts = { 14 } },
	[288] = { arms = 3, validShirts = { 14 } },
	[289] = { arms = 3, validShirts = { 14 } },
	[290] = { arms = 3, validShirts = { 14 } },
	[291] = { arms = 3, validShirts = { 14 } },
	[292] = { arms = 3, validShirts = { 14 } },
	[293] = { arms = 3, validShirts = { 14 } },
	[294] = { arms = 4, validShirts = { 14 } },
	[295] = { arms = 14, validShirts = { 14 } },
	[296] = { arms = 207, validShirts = { 14 } },
	[297] = { arms = 215, validShirts = { 14 } },
	[298] = { arms = 3, validShirts = { 14 } },
	[299] = { arms = 3, validShirts = { 14 } },
	[300] = { arms = 8, validShirts = { 14 } },
	[301] = { arms = 11, validShirts = { 14 } },
	[302] = { arms = 11, validShirts = { 14 } },
};
